name: Bot Shopee
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install requests
      - run: python Bot.py
